### Importing the libraries

In [9]:
import pandas 
import numpy 
from datetime import datetime

In [2]:
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Laptop", "Smartphone", "Headphones", "Smart Watch"],
    "Category": ["Electronics", "Electronics", "Accessories", "Wearables"],
    "Price": [1200, 850, 150, 300],
    "Stock": [15, 30, 50, 20]
})
print("PRODUCT INVENTORY")
display(products)

PRODUCT INVENTORY

   ProductID  ProductName     Category  Price  Stock
0        101       Laptop  Electronics   1200     15
1        102   Smartphone  Electronics    850     30
2        103   Headphones  Accessories    150     50
3        104  Smart Watch    Wearables    300     20

In [3]:
orders = pd.DataFrame({
    "OrderID": [1001, 1002, 1003],
    "Customer": ["John", "Emma", "David"],
    "Product": ["Laptop", "Headphones", "Smartphone"],
    "Quantity": [1, 2, 1],
    "OrderDate": [
        "2026-05-01",
        "2026-05-03",
        "2026-05-05"
    ]
})
print("\n CUSTOMER ORDERS ")
display(orders)

 CUSTOMER ORDERS

   OrderID Customer     Product  Quantity   OrderDate
0     1001     John      Laptop         1  2026-05-01
1     1002     Emma  Headphones         2  2026-05-03
2     1003    David  Smartphone         1  2026-05-05

In [4]:
price_lookup = {
    "Laptop": 1200,
    "Headphones": 150,
    "Smartphone": 850
}

orders["TotalPrice"] = orders.apply(
    lambda row: row["Quantity"] * price_lookup[row["Product"]],
    axis=1
)

print("\n SALES REPORT ")
display(orders)
total_sales = orders["TotalPrice"].sum()
print(f"\nTotal Revenue Generated: €{total_sales}")

 SALES REPORT

   OrderID Customer     Product  Quantity   OrderDate  TotalPrice
0     1001     John      Laptop         1  2026-05-01        1200
1     1002     Emma  Headphones         2  2026-05-03         300
2     1003    David  Smartphone         1  2026-05-05         850

Total Revenue Generated: €2350

In [5]:
low_stock = products[products["Stock"] < 20]
print("\n LOW STOCK ALERT ")
if not low_stock.empty:
    display(low_stock)
else:
    print("All products have a sufficient stock.")

 LOW STOCK ALERT

   ProductID ProductName     Category  Price  Stock
0        101      Laptop  Electronics   1200     15

In [6]:
server_logs = pd.DataFrame({
    "Timestamp": [
        datetime.now(),
        datetime.now(),
        datetime.now()
    ],
    "Service": [
        "EC2 Instance",
        "RDS Database",
        "CloudFront CDN"
    ],
    "Status": [
        "Running",
        "Connected",
        "Active"
    ]
})

print("\n AWS CLOUD SERVICES STATUS ")
display(server_logs)

 AWS CLOUD SERVICES STATUS

                   Timestamp         Service     Status
0 2026-05-07 15:46:57.531772    EC2 Instance    Running
1 2026-05-07 15:46:57.531776    RDS Database  Connected
2 2026-05-07 15:46:57.531776  CloudFront CDN     Active

In [7]:
response_times = np.random.randint(100, 500, size=10)
avg_response = np.mean(response_times)
print("\n  PERFORMANCE METRICS ")
print(f"Average API Response Time: {avg_response:.2f} ms")
if avg_response < 300:
    print("Application Performance Status: OPTIMIZED")
else:
    print("Application Performance Status: NEEDS IMPROVEMENT")

  PERFORMANCE METRICS
Average API Response Time: 244.70 ms
Application Performance Status: OPTIMIZED